var SpeakerDetails = [
    {   
        id:1,
        register:0,
        eventname: "SHARK TANK 1",
        time:"9:00 - 10:00",
        name: 'Aman Gupta',
        imagesrc : require('./images/Speakers/aman1.jpg'),
        occ: 'Founder, Boat',
        desicription : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
        
    },
    {   id:2, 
        register:1,
        eventname: "SHARK TANK 2",
        time:"10:00 - 11:00",
        name: 'Aman Gupta',
        imagesrc : require('./images/Speakers/aman2.jpg'),
        occ: 'Founder, Boat',
        desicription : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
    },
    {    id:3,
        eventname: "SHARK TANK 3",
        time:"11:00 - 12:00",
        name: 'Aman Gupta',
        imagesrc : require('./images/Speakers/aman1.jpg'),
        occ: 'Founder, Boat',
        desicription : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
    },
    {    id:4,
        eventname: "SHARK TANK 4",
        time:"12:00 - 1:00",
        name: 'Aman Gupta',
        imagesrc : require('./images/Speakers/aman2.jpg'),
        occ: 'Founder, Boat',
        desicription : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
    },
    {   id:5, 
        eventname: "SHARK TANK 5",
        time:"1:00 - 2:00",
        name: 'Aman Gupta',
        imagesrc : require('./images/Speakers/aman1.jpg'),
        occ: 'Founder, CEO',
        desicription : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
    },
    {    id:6,
        eventname: "SHARK TANK 6",
        time:"2:00 - 3:00",
        name: 'Aman Gupta',
        imagesrc : require('./images/Speakers/aman2.jpg'),
        occ: 'Founder, CEO',
        desicription : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
    },
    {   id:7, 
        eventname: "SHARK TANK 7",
        time:"3:00 - 4:00",
        name: 'Aman Gupta',
        imagesrc : require('./images/Speakers/aman1.jpg'),
        occ: 'Founder, CEO',
        desicription : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
    },
    {    id:8,
        eventname: "SHARK TANK 8",
        time:"4:00 - 5:00",
        name: 'Aman Gupta',
        imagesrc : require('./images/Speakers/aman2.jpg'),
        occ: 'Founder, CEO',
        desicription : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
    },

    
]


export default SpeakerDetails